# Generated by Django 4.2.7 on 2024-03-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApniDukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=500)),
                ('area', models.CharField(max_length=200)),
                ('about', models.CharField(blank=True, max_length=1000)),
                ('delivery_detail', models.CharField(blank=True, max_length=2000)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('whatsapp_number', models.CharField(blank=True, max_length=10)),
                ('owner_image', models.ImageField(upload_to='apnidukan/dukanowner/')),
                ('banner_image', models.ImageField(upload_to='apnidukan/dukanbanner/')),
            ],
        ),
    ]
