# Generated by Django 4.2.7 on 2024-03-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukandar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apnidukan',
            name='delivery_detail',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
