# Generated by Django 4.2.7 on 2024-03-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dukandar', '0001_initial'),
        ('User', '0006_user_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='defaultDukan',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dukandar.apnidukan'),
        ),
    ]
