# Generated by Django 4.2.7 on 2024-03-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_user_defaultdukan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='defaultDukan',
            new_name='default_dukan',
        ),
    ]
