# Generated by Django 4.1.4 on 2023-11-01 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_rename_total_product_category_total_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCompleted', models.BooleanField(default=False)),
                ('isDeliverd', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('deliverdAt', models.DateTimeField(blank=True, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('price', models.FloatField(default=0)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
