# Generated by Django 4.1.4 on 2023-11-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isCompleted',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='isDeliverd',
            new_name='is_deliverd',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='isPaid',
            new_name='is_paid',
        ),
    ]
