# Generated by Django 4.1.4 on 2023-11-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_item',
            field=models.IntegerField(default=0),
        ),
    ]
