# Generated by Django 4.2.7 on 2023-12-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
    ]
