# Generated by Django 4.2.7 on 2023-12-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deliverdAt',
            new_name='deliverd_at',
        ),
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='order_city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='order_house_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_phone_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
