# Generated by Django 4.2.7 on 2023-12-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_createdat_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
