# Generated by Django 4.2.7 on 2024-02-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_list',
            field=models.ImageField(blank=True, upload_to='orderlist/'),
        ),
    ]
