# Generated by Django 4.2.7 on 2024-02-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_order_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
    ]
