# Generated by Django 4.2.7 on 2024-03-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_orderitem_item_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
