# Generated by Django 4.2.7 on 2024-03-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
    ]
