# Generated by Django 4.2.7 on 2024-03-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
