# Generated by Django 4.1.4 on 2023-11-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='total_product',
            new_name='total_products',
        ),
    ]
