# Generated by Django 4.2.7 on 2024-02-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.IntegerField(default=0),
        ),
    ]
