# Generated by Django 4.2.7 on 2024-02-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_discount_product_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
