# Generated by Django 4.2.7 on 2024-03-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_name',
        ),
    ]
