# Generated by Django 4.2.7 on 2024-03-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dukandar', '0001_initial'),
        ('product', '0013_remove_product_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dukan',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dukandar.apnidukan'),
        ),
    ]
