# Generated by Django 4.2.7 on 2024-03-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukandar', '0003_apnidukan_is_active'),
        ('product', '0014_product_dukan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dukan',
        ),
        migrations.AddField(
            model_name='product',
            name='dukan',
            field=models.ManyToManyField(default='1', to='dukandar.apnidukan'),
        ),
    ]
