# Generated by Django 4.2.7 on 2024-03-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dukandar', '0003_apnidukan_is_active'),
        ('product', '0015_remove_product_dukan_product_dukan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dukan',
        ),
        migrations.AddField(
            model_name='product',
            name='dukan',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dukandar.apnidukan'),
        ),
    ]
