# Generated by Django 4.2.7 on 2023-12-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.TextField(default='', max_length=4000),
        ),
    ]
