# Generated by Django 4.2.7 on 2024-02-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_notification_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreview',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
