# Generated by Django 4.2.7 on 2024-03-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_apnidukan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApniDukan',
        ),
    ]
